### PR TITLE
Bug/issue 6

### LINKED ISSUE #5: Changing Java package name
Currently we are using as Java package name:

es.tid.fiware.perseo;

It will be desirable to align this with Sonar naming, thus it could be:

com.telefonica.iot.perseo;

**Effort: 1 man day**

### PR DESCRIPTION
**Pull request by crbrox**
Closes #5 #6 
@fgalan 
@jcalderin

### CODE REVIEW

File: CHANGES_NEXT_RELEASE [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Change package name
+FIX Long rule set
```
Comment (fgalan) [inline CHANGES_NEXT_RELEASE]: In this case, given this PR is fixing an issue "with number" it could be included in the entry. I.e.:

"FIX Long rule set (#6)"

File: src/main/java/com/telefonica/iot/perseo/Configuration.java [hunk 2]
```diff
@@ -18,7 +18,7 @@
 * iot_support at tid dot es
 */
 
-package es.tid.fiware.perseo;
+package com.telefonica.iot.perseo;
```
Comment (fgalan) [inline src/main/java/com/telefonica/iot/perseo/Configuration.java]: I understand that you are also solving https://github.com/telefonicaid/perseo-core/issues/5 in this PR. Great!

However, don't forget to mention in the CHANGES_NEXT_RELEASE file, e.g.

"Chaning the name of the Java package to com.telefonica.iot.perseo"

or something similar.

File: CHANGES_NEXT_RELEASE (hunk 1 above)
Comment (crbrox) [inline CHANGES_NEXT_RELEASE]: Fixed 6fe910b

File: src/main/java/com/telefonica/iot/perseo/Configuration.java (hunk 2 above)
Comment (crbrox) [inline src/main/java/com/telefonica/iot/perseo/Configuration.java]: Fixed f8b6c9d

**Comment by fgalan** [comment]
LGTM

**Comment by jcalderin** [comment]
As a comment that not blocks the merge, this code:

```
+            StringBuilder sb = new StringBuilder();
+            BufferedReader br = request.getReader();
+            String read = br.readLine();
+            while (read != null) {
+                sb.append(read);
+                read = br.readLine();
+            }
```

Is repeated inside three functions, for maintainability it could be good to write it in a separate util function.

**Comment by crbrox** [comment]
Fixed 950ee45

**Comment by jcalderin** [comment]
LGTM
